name: "Auto test PR"
on:
  issue_comment:
    types: [created]
permissions:
      contents: write
      issues: write
jobs:
  autoTestPR:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, 'auto exclude test')
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: 3.8
      - name: check python version
        run: |
          python -V
      - name: install xml module
        run: |
          pip install lxml
      - name: checkout current repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          path: 'tests'
      - name: checkout TKG repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: 'adoptium/TKG.git'
          ref: 'master'
          path: 'TKG'
      - name: run script
        env:
          comment_body: ${{ github.event.comment.body }}
        run: |
          git config --list
          python TKG/scripts/testBot/disable.py -m "$comment_body" -c "${{ github.event.comment.html_url }}" -d "$GITHUB_WORKSPACE/tests"
      - name: test cannot be found
        if: failure()
        run: |
          curl -u github-actions:${{ secrets.GITHUB_TOKEN }} -d '{ "body":  "The specified test cannot be excluded. Action run: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}" }' -X POST ${{ github.event.issue.comments_url }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        with:
          path: 'tests'
          title: '${{ github.event.comment.body }}'
          body: |
            related: ${{ github.event.comment.html_url }}
            triggered by @${{ github.event.comment.user.login }}
          commit-message: |
            AUTO: ${{ github.event.comment.body }}
            - related: ${{ github.event.comment.html_url }}
          branch: 'autoTestPR'
          branch-suffix: 'random'
          signoff: 'true'
      - name: add label
        run: |
          curl -u github-actions:${{ secrets.GITHUB_TOKEN }} -d '{"labels":["test excluded"]}' -X POST ${{ github.event.issue.url }}/labels
